linters:
  enable-all: true
  disable:
    - gci
    - gofumpt
    - goimports
    - exhaustivestruct
    - scopelint
    - interfacer
    - maligned
    - golint
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - tparallel
    - wastedassign
linters-settings:
  gomnd:
    ignored-functions:
      - strconv.ParseInt
      - strconv.ParseUint
      - strconv.ParseFloat
      - time.Sleep
  paralleltest:
    ignore-missing: true
  exhaustruct:
    exclude:
      - "bonds_calculator/internal/model/moex.*"
      - "net/http.*"
      - "github.com/gofiber/fiber/v2.*"
      - "github.com/go-redis/redis/v9.*"
  wrapcheck:
    ignorePackageGlobs:
      - "github.com/gofiber/fiber/*"
      - "golang.org/x/sync/singleflight*"
      - "bonds_calculator/internal/controller/util"
  
