version: "3.8"

services:

  web:
    build:
        context: .
        target: run
    ports:
      - "8080:8080"
    links:
      - redis
      - postgres
    restart: always
    environment:
      - CONFIG_DB_HOST=postgres
      - CONFIG_REDIS_HOST=redis

  web-tests:
    build:
      context: .
      target: test

  redis:
    image: redis:7
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: bonds_calculator
      POSTGRES_PASSWORD: bonds_calculator
    ports:
      - "127.0.0.1:5432:5432"
