version: "3"
tasks:
  build:
    cmds:
      - go build -o out/app cmd/main.go
  test:
    cmds:
      - go test -v ./...
  generate:
    cmds:
      - go generate ./...
  prepare:
    cmds:
      - go mod download
      - go mod vendor
  run:
    cmds:
      - go run cmd/main.go
