version: "3"
tasks:
  dependencies:
    cmds:
      - go mod download
  generate:
    cmds:
      - go generate ./...
      - go generate wire ./...
  prepare:
    cmds:
      - task: dependencies
      - task: generate
  build:
    cmds:
      - go build -o ./out/bc ./cmd/main.go
  test:
    cmds:
      - CGO_ENABLED=0 GOOS=linux go test -v ./...
  run:
    cmds:
      - go run ./...
