version: "3"
tasks:
  dependencies:
    cmds:
      - go mod download
  generate:
    cmds:
      - go generate internal/data/schema/generate.go
      - go generate -tags wireinject ./...
  prepare:
    cmds:
      - task: dependencies
      - task: generate
  lint:
    cmds:
      - golangci-lint run
  build:
    cmds:
      - go build -o ./out/bc ./cmd/main.go
  test:
    cmds:
      - CGO_ENABLED=0 GOOS=linux go test -v ./...
  test-ci:
    cmds:
      - CI=true CGO_ENABLED=0 GOOS=linux go test -v ./...
  run:
    cmds:
      - go run ./...
